# Generated by Django 5.1.5 on 2025-02-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='modified_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_date',
            new_name='updated_date',
        ),
    ]
